version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app
    depends_on:
      - redis
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

  redis:
    image: redis:6-buster
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    #command: ["redis-server", "--appendonly", "yes"]

volumes:
  redisdata:
